### ISSUE TITLE
Fatal error on protocol

### ISSUE THREAD

**Issue by macintoshplus** [acropia/PHP-WinRM#1]
Hi,

I want test your library for use WinRM, but I have many error.

```
PHP Fatal error:  Uncaught Error: Call to a member function setDefault() on array in /Sites/PHP-WinRM/winrm/protocol.php:77
Stack trace:
#0 /Sites/PHP-WinRM/winrm/winrm.php(60): protocol->openShell()
#1 /Sites/PHP-WinRM/winrm/index.php(9): Session->runCommand('ipconfig', '/all')
#2 {main}
  thrown in /Sites/PHP-WinRM/winrm/protocol.php on line 77
```

You don't have mentioned none requirement for use. What is the problem ?

Thanks in advance

**Comment by macintoshplus** [comment]
No response !
This project is dead ?
